### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cschroed-usgs**
Addressing #75.

### CODE REVIEW

**Comment by jiwalker-usgs** [comment]
Is there any configuration beyond this that is necessary?

**Comment by mbucknell** [comment]
There are a whole set of JNDI properties needed in order to run this. The app is pretty tightly coupled to the gdp wps processing server.

**Comment by cschroed-usgs** [comment]
@jiwalker-usgs , maybe. Thanks for bringing it up. @mbucknell, @isuftin , correct me if I'm wrong, but I think we were keeping an context.xml in a google doc somewhere instead of checking an exampleContext.xml in to the repo like we do on most other projects. Our collaborator's interest in running the project highlights the weakness of the google drive approach. We prefer reproducible builds.

**Comment by mbucknell** [comment]
The configuration for this app is actually controlled by a set of files in stash that use ansible. We are no longer maintaining that google doc.

**Comment by cschroed-usgs** [comment]
That's good to hear. I'll defer to you on whether it's better to include that file from the stash repo in the github repo, or send the file to Rich directly.

**Pull request merged**
